default_language_version:
    python: python3.11
files: '.py'
exclude: ".env,.yml,.gitignore,.git,.md,.txt"
default_stages: [push, commit]
repos:
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -  id: bandit
       args: ["-c", "pyproject.toml"]
       name: Bandit
       stages: [commit]
       additional_dependencies: ["bandit[toml]"]
       
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        name: Black
        stages: [commit]
        
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
    -   id: autoflake
        args: ["--in-place", "--remove-unused-variables", "--remove-all-unused-imports", "--recursive"]
        name: AutoFlake
        description: "Format with AutoFlake"
        stages: [commit]
        
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: ISort
        description: "Format with Isort"
        stages: [commit]


