# --------------------------------- #
#    Rodhaj's Configuration file    #
# --------------------------------- #
# This holds the configuration for Rodhaj. This file is not settable during runtime.
# If you wish to change the values, change and save, and restart your bot

# Entries pertaining to Rodhaj are located here
rodhaj:

  # The token that Rodhaj will use.
  # Ensure that this is kept secret, as these are just like the password to your bot.
  token: ""

  # The Guild ID that is associated with Rodhaj. This will be the guild that Rodhaj
  # will operate in, and will be the guild that Rodhaj will use to associate tickets and co.
  guild_id: 12345

  # The dev mode for Rodhaj. This will enable certain features
  # such as an extension and library hot reloader in order to
  # make development easier
  # Note: Set this to false or remove this entry when running Rodhaj in production
  dev_mode: False

  # Prometheus exporter for Rodhaj. The following keys are used in order to control
  # the behavior of the Prometheus exporter
  prometheus:

    # Whether the Prometheus exporter is enabled or not
    enabled: False

    # The host that the Prometheus exporter will bind to. By default,
    # it will always be set to 127.0.0.1
    host: "127.0.0.1"

    # The port used for the Prometheus exporter. By default,
    # it will always be set to 8555
    port: 8555

# The PostgreSQL connection URI that is used to connect to the database
# The URI must be valid, and components will need to be quoted.
# See https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
postgres_uri: "postgresql://user:password@localhost:5432/user"
