version: "3.9"
name: "rodhaj-dev"
services:
  postgres:
    container_name: Rodhaj-Postgres
    image: rodhaj-pg:dev-latest
    build:
      context: ./docker/pg
      dockerfile: Dockerfile
    env_file:
      - docker.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_volume:
