[tool.poetry]
name = "rodhaj"
version = "0.1.0"
description = "Trnasprogrammer discord bot"
authors = ["No767 <73260931+No767@users.noreply.github.com>"]
license = "MPL-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
discord-py = {extras = ["speed"], version = "^2.3.2"}
python-dotenv = "^1.0.0"
uvloop = {markers = "sys_platform != \"win32\"", version = "^0.19.0"}
asyncpg = "^0.28.0"
discord-ext-menus = {git = "https://github.com/Rapptz/discord-ext-menus", rev = "8686b5d1bbc1d3c862292eb436ab630d6e9c9b53"}
psutil = "^5.9.6"
pygit2 = "^1.13.2"
python-dateutil = "^2.8.2"
click = "^8.1.7"
typing-extensions = "^4.8.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.5.0"
pyright = "^1.1.334"
ruff = "^0.1.3"
watchfiles = "^0.21.0"
jishaku = "^2.5.2"

[tool.isort]
profile = 'black'

[tool.pyright]
include = ["bot/**"]
exclude = [
    "**/__pycache__", 
    "**/.mypy_cache", 
    "**/.dmpypy.json", 
]
reportMissingImports = true
typeCheckingMode = "basic"
reportUnnecessaryTypeIgnoreComment = "warning"

[tool.bandit]
skips = ["B311", "B101"]

[tool.ruff]
ignore = ["E501", "N999", "E402"]
select = ["E", "F", "N", "ASYNC", "S", "ERA"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
