[tool.poetry]
name = "rodhaj"
version = "0.2.0"
description = "Transprogrammer's custom modmail bot"
authors = ["No767 <73260931+No767@users.noreply.github.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4"
discord-py = {extras = ["speed"], version = "^2.3.2"}
uvloop = {markers = "sys_platform != \"win32\"", version = "^0.19.0"}
winloop = {markers = "sys_platform == \"win32\"", version = "^0.1.1"}
asyncpg = "^0.29.0"
discord-ext-menus = {git = "https://github.com/Rapptz/discord-ext-menus", rev = "8686b5d1bbc1d3c862292eb436ab630d6e9c9b53"}
psutil = "^5.9.8"
pygit2 = "^1.14.1"
python-dateutil = "^2.9.0"
click = "^8.1.7"
async-lru = "^2.0.4"
msgspec = "^0.18.6"
jishaku = "^2.5.2"
pyyaml = "^6.0.1"
watchfiles = "^0.21.0"
typing-extensions = "^4.10.0"

[tool.poetry.group.dev.dependencies]
# These are pinned by major version
# To not get dependabot to constantly update them
# https://python-poetry.org/docs/dependency-specification/
pre-commit = "^3"
pyright = "^1.1"
ruff = "^0.3"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
sphinx-autobuild = "^2024.2.4"
sphinx-copybutton = "^0.5.2"
furo = "^2024.1.29"

[tool.isort]
profile = 'black'
combine_as_imports = true
combine_star = true
line_length = 80

[tool.pyright]
include = ["bot/**"]
exclude = [
    "**/__pycache__", 
    "**/.mypy_cache", 
    "**/.dmpypy.json", 
]
reportMissingImports = true
typeCheckingMode = "basic"
reportUnnecessaryTypeIgnoreComment = "warning"

[tool.bandit]
skips = ["B311", "B101"]

[tool.ruff]
ignore = ["E501", "N999", "E402", "S311"]
select = ["E", "F", "N", "ASYNC", "S", "ERA"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
