#!/usr/bin/env bash

RODHAJ_FIRST_START_CHECK="RODHAJ_FIRST_START"

if [ ! -f $RODHAJ_FIRST_START_CHECK ]; then
    touch $RODHAJ_FIRST_START_CHECK
    echo "DO NOT EDIT THIS FILE! THIS IS USED WHEN YOU FIRST RUN RODHAJ USING DOCKER!" >> $RODHAJ_FIRST_START_CHECK
    python3 /rodhaj/bot/migrations.py init
fi

exec python3 /rodhaj/bot/launcher.py